apiVersion: v1
kind: Service
metadata:
  name: jsf-k8s-service
  labels:
    app: jsf-k8s-app
spec:
  selector:
    app: jsf-k8s-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
